export const PROJECTS = [
  {
    id: '01', year: '2024', client: 'Vera Health',
    role: 'Lead Product Designer',
    title: 'An AI clinical assistant doctors actually trust',
    tags: ['Healthcare', 'AI', 'iOS'],
    metric: 'Used in 1,200+ shifts',
    image: 'assets/case-vera.webp',
    href: 'vera-health.html',
    color: 'oklch(0.92 0.02 240)',
  },
  {
    id: '03', year: '2024', client: 'Podlify',
    role: 'Product Designer',
    title: 'A control room for podcast creators',
    tags: ['Media', 'Analytics', 'Dashboard'],
    metric: 'Creator analytics suite',
    image: 'assets/case-podlify.webp',
    href: 'podlify.html',
    color: 'oklch(0.40 0.10 300)',
  },
  {
    id: '05', year: '2024', client: 'BXYZ',
    role: 'Product Designer',
    title: 'Fantasy basketball that trades like a live market',
    tags: ['Web3', 'Gaming', 'Dashboard'],
    metric: 'Fantasy trading platform',
    image: 'assets/case-bxyz.webp',
    href: 'bxyz.html',
    color: 'oklch(0.32 0.05 55)',
  },
  {
    id: '07', year: '2024', client: 'VoltRide',
    role: 'Product Designer',
    title: 'EV car-sharing, reserved in a few taps',
    tags: ['Mobility', 'iOS', 'EV'],
    metric: 'End-to-end iOS app',
    image: 'assets/case-voltride.webp',
    href: 'voltride.html',
    color: 'oklch(0.85 0.15 125)',
  },
  {
    id: '02', year: '2024', client: 'Down Dating',
    role: 'Senior Product Designer',
    title: "A dating app for the things people don't say out loud",
    tags: ['Dating', '18+', 'iOS'],
    metric: 'Consumer dating app',
    image: 'assets/case-downdating.webp',
    href: 'down-dating.html',
    color: 'oklch(0.72 0.10 330)',
  },
  {
    id: '04', year: '2024', client: 'Fortytwo.io',
    role: 'Product Designer',
    title: 'Security posture, made legible for whole teams',
    tags: ['SaaS', 'Security', 'Azure'],
    metric: 'Identity & access SaaS',
    image: 'assets/case-fortytwo.webp',
    href: 'fortytwo.html',
    color: 'oklch(0.80 0.12 160)',
  },
  {
    id: '06', year: '2023', client: 'VanCity Drafting',
    role: 'Product Designer',
    title: 'An architectural visualization studio, online',
    tags: ['Web', 'Architecture', 'Branding'],
    metric: 'Vancouver, BC studio',
    image: 'assets/case-vancity.webp',
    href: 'vancity.html',
    color: 'oklch(0.40 0.05 215)',
  },
  {
    id: '08', year: '2023', client: 'CryptoHub',
    role: 'Product Designer',
    title: "A crypto exchange that doesn't look like a casino",
    tags: ['Fintech', 'Web', 'Crypto'],
    metric: 'Bestchange 4.8',
    image: 'assets/case-cryptohub.webp',
    href: 'cryptohub.html',
    color: 'oklch(0.30 0.05 165)',
  },
];

export const EXPERIENCE = [
  {
    period: '2021 — Present',
    company: 'Awesomic',
    role: 'Senior Product Designer',
    desc: 'Designing mobile apps, AI tools, dashboards, SaaS platforms, and high-conversion web experiences for U.S & EU tech companies. Delivering fast, scalable UX/UI solutions across diverse product teams.',
    logo: 'assets/awesomic.svg',
    accent: '#FEFEFE',
  },
  {
    period: '2024 — 2025',
    company: 'Powerhouse AI',
    role: 'Product Designer',
    desc: 'Designed complex workflows and dashboard interfaces for AI-powered automation tools used by legal teams. Contributed to UX architecture, data visualization, and product feature development.',
    logo: 'assets/powerhouse.svg',
    accent: '#101D49',
  },
  {
    period: '2022 — 2024',
    company: 'Logolivery',
    role: 'Digital Designer',
    desc: 'Created websites, apps, landing pages, branding systems, and identity assets. Worked across multiple industries, delivering clean and modern UI solutions.',
    logo: 'assets/logolivery.svg',
    accent: '#8C76FB',
  },
];

export const SERVICES = [
  { n: '01', t: 'Product & UX Strategy', d: 'Translating business goals into product structure, user flows, and clear UX architecture that scales as the team grows.' },
  { n: '02', t: 'AI & Complex Tools Design', d: 'Designing AI-powered tools, automations, and complex workflows where clarity, control, and trust matter most.' },
  { n: '03', t: 'Mobile App Design', d: 'Creating intuitive, high-quality mobile experiences with strong interaction design, navigation logic, and platform-native patterns.' },
  { n: '04', t: 'Dashboard & SaaS Platforms', d: 'Building data-dense interfaces — admin panels, analytics, and B2B platforms — that stay readable and fast under real workloads.' },
  { n: '05', t: 'Visual Systems & Design Language', d: 'Establishing design tokens, components, and patterns so teams ship consistently without reinventing the wheel each sprint.' },
  { n: '06', t: 'Delivery & Collaboration', d: 'Working closely with PMs and engineers — fast iterations, tight feedback loops, and design that ships, not just looks good in Figma.' },
];
